// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = function(db) {
    return {
      get: function(id, callback) {
        var rs;
        rs = db.createReadStream();
        console.log(rs);
        rs.on('error', callback);
        rs.on('data', function(data) {
          return callback(null, data.value);
        });
        return rs.on('close', callback);
      },
      save: function(id, metrics, callback) {
        var i, len, metric, timestamp, value, ws;
        ws = db.createWriteStream();
        ws.on('error', callback);
        ws.on('close', callback);
        for (i = 0, len = metrics.length; i < len; i++) {
          metric = metrics[i];
          timestamp = metric.timestamp, value = metric.value;
          ws.write({
            key: "metrics:" + id + ":" + timestamp,
            value: value
          });
        }
        return ws.end();
      }
    };
  };

}).call(this);
