// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = function(db) {
    return {
      get: function(username, callback) {
        return db.get("user:" + username, function(err, data) {
          var email, ref, result;
          if (err) {
            throw err;
          }
          if (data === null) {
            callback(null, null);
          }
          ref = data.split(":"), username = ref[0], email = ref[1];
          result = {
            username: username,
            password: data.split(":")[0],
            email: email
          };
          return callback(null, result);
        });
      },
      save: function(username, passwd, email, callback) {
        var ws;
        ws = db.createWriteStream();
        ws.on('error', callback);
        ws.on('close', callback);
        ws.write({
          key: "user:" + username,
          value: passwd + ":" + email
        });
        return ws.end();
      },
      remove: function(username, callback) {}
    };
  };

}).call(this);
