// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = function(db) {
    return {
      get: function(username_sent, password_sent, callback) {
        return db.get("user:" + username_sent, function(err, data) {
          var result, rs;
          result = {};
          rs = db.createReadStream();
          rs.on('data', function(data) {
            var email, password, ref, ref1, user, username;
            ref = data.key.split(":"), user = ref[0], username = ref[1];
            ref1 = data.value.split(":"), password = ref1[0], email = ref1[1];
            if (username === username_sent && password === password_sent) {
              return result = {
                username: username,
                password: password,
                email: email
              };
            }
          });
          rs.on('error', function() {});
          rs.on('close', function() {});
          return rs.on('end', function() {
            return callback(null, result);
          });
        });
      },
      save: function(username, passwd, email, callback) {
        var ws;
        ws = db.createWriteStream();
        ws.on('error', callback);
        ws.on('close', callback);
        ws.write({
          key: "user:" + username,
          value: passwd + ":" + email
        });
        return ws.end();
      },
      remove: function(username, callback) {}
    };
  };

}).call(this);
